app/main/routes.py
from flask       import render_template, url_for, flash, redirect, request, Blueprint,jsonify
from flask_login import login_user, current_user, logout_user, login_required
from datetime    import datetime
from app         import db, bcrypt
from app.models  import User,Task

main = Blueprint('main', __name__)

@main.route('/', methods=['GET', 'POST'])
@main.route('/home', methods=['GET', 'POST'])
def home():
    tasks = Task.query.all()
    return render_template('tasker/dashboard.html',tasks=tasks)

@login_required
@main.route('/user_list')
def user_list():
    
    users = User.query.all()
    user_list = [{'id':user.id,'username':user.username} for user in users]
    
    return jsonify({'users':user_list})

app/tasker/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint,jsonify
from flask_login import login_user, current_user, logout_user, login_required
from app import db, bcrypt
from app.models import User,Task
from app.tasker.forms import AddTaskForm
from datetime import datetime


tasker = Blueprint('tasker', __name__)

@tasker.route('/create_task', methods=['GET','POST'])
def create_task():
    
    form = AddTaskForm()
    
    users = User.query.all()
    tasks = Task.query.all()
    
    if form.validate_on_submit():
        user = User.query.filter_by(id=current_user.id).first()
        task_name   = form.task_name.data
        task_detail = form.task_detail.data
        task_date   = form.task_date.data
        assigned_to = form.assigned_to.data
        
        task = Task(id=len(tasks)+1,task_name=task_name,task_detail=task_detail,task_date=task_date,
                    assigned_to=assigned_to,assigned_by=user.username,assigner_mail = user.email,
                    assigner_phone=user.phone)
        
        db.session.add(task)
        db.session.commit()
        flash('Task has been succesfully created','success')
        
        return redirect(request.referrer)
        
    
    return render_template('tasker/create_task.html', form=form,users=users)


@login_required
@tasker.route("/update_task/<task_id>/<status>")
def update_task(task_id,status):
    task = Task.query.filter_by(task_id=task_id).first()
    
    task.status = status
    db.session.merge(task)
    db.session.flush()
    db.session.commit()
    
    flash(f"Task {task.task_name} has been updated","success")
    return redirect(request.referrer)

status_list = ['Success','Extended','Complete','Incomplete','Reassigned']

@login_required
@tasker.route("/task_status_list")
def list_status():
    stats = [{'id':i,'status':status} for i,status in enumerate(status_list)]
    return jsonify(stats)

@login_required
@tasker.route("/list_tasks")
def list_task():
    tasks = Task.query.filter_by(assigned_by=current_user.id).all()
    task_list = [task.serialize for task in tasks]
    return jsonify(tasks)

app/users/routes.py
from flask       import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from datetime    import datetime
from app         import db, bcrypt
from app.models  import User,Task
from itsdangerous import URLSafeTimedSerializer
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from email.message import EmailMessage
from app.users.forms import RegistrationForm, LoginForm
import smtplib

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        # use this for email confirmation
        #token = generate_confirmation_token(user.email)
        #confirm_url = url_for('confirm_email', token=token, _external=True)
        #html = render_template('users/activate.html', confirm_url=confirm_url)
        #subject = "Please confirm your email"
        #send_email(user.email,subject, html)

        flash('A confirmation email has been sent via email.', 'success')
        return redirect(url_for('main.home'))
    return render_template('users/register.html', form=form, title='Register now',
                           description='Registration form for new users')

def generate_confirmation_token(email):
    serializer = URLSafeTimedSerializer(current_app.config['SECRET_KEY'])
    return serializer.dumps(email, salt=current_app.config['SECURITY_PASSWORD_SALT'])

def send_email(to,subject, template):
    message = EmailMessage()
    message['To']      = to
    message['From']    = MAIL_DEFAULT_SENDER
    message['Subject'] = subject
    message.set_content(template, subtype='html')
    with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:
        smtp.login(EMAIL_USER, EMAIL_PASS)
        smtp.send_message(message)

@users.route('/confirm/<token>')
def confirm_email(token):
    try:
        email = confirm_token(token)
    except:
        flash('The confirmation link is invalid or has expired.', 'danger')
    user = User.query.filter_by(email=email).first_or_404()
    if user.join_date:
        flash('Account already confirmed. Please login.', 'success')
    else:
        user.user_type = 1
        user.join_date = datetime.now()
        db.session.add(user)
        db.session.commit()
        flash('You have confirmed your account. Thanks!', 'success')
        flash('Go to account page to update your details', 'info')
    return redirect(url_for('main.home'))

@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('users/login.html', form=form, title='Login',
                           description="Login page for existing users")

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

app/templates/home.html
{% extends "layout.html" %}


{% block content %}
<h1 class="title">Task manager</h1>
<p> under construction</p>

{#
<p><a href="{{url_for('task_list')}}">task list</a></p>
<p><a href="{{url_for('list_status')}}">status list</a></p>

#}

{% endblock content %}

app/templates/layout.html
<!DOCTYPE html>
<html>

<!-- head and meta tags -->
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link href="static/css/base.css" rel="stylesheet"/>

<title> Task manager </title>

</head>

<!-- Body -->
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Company</a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="{{url_for('main.home')}}"> Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link btn btn-outline-secondary my-2 my-sm-0 mx-2" href="{{url_for('tasker.create_task')}}">New Task</a>
      </li>
    </ul>
    <ul class="nav navbar-nav ml-auto">
    {% if current_user.is_authenticated %}
        <li class="nav-item" role="presentation"><a class="nav-item nav-link" href="#">{{current_user.username}}</a></li>
        <li class="nav-item" role="presentation"><a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a></li>
    {% else %}
        <li class="nav-item" role="presentation"><a class="nav-item nav-link" href="{{ url_for('users.login') }}"> Login</a></li>
        <li class="nav-item" role="presentation"><a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a></li>
    {% endif %}
    </ul>
  </div>
</nav>

<main class="col-12 mx-0 pt-5">
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
            {{ message }}
        </div>
        {% endfor %}
    {% endif %}
{% endwith %}

{% block content %}{% endblock %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

</body>
<!-- end body -->

</html>